export let survey = {
    id: 0,
    projectid: 0,
    name: '',
    description: '',
    showname: '',
    content: '',
    use_raw_content: 0,
    htmlid: '',
    groupid: '',
    complexid: '',
    exectime: '',
    maxentries: 0,
    itemscount: 0,
    checkresult: '1',
    showresult: '1',
    percentrigth: 70,
    saveprogress: '0',
    attemptsinfo: '1',
    shufflequestions: '0',
    shufflegroups: '0',
    shuffleanswers: 0,
    excludetypes: '["html", "image"]',
    countbygroups:'{}',
    showcustompanel: '0',
    updateinterval: 2000,
    created_at: '',
    modified_at: ''
}