export let question_object = {
    order_id: 0,
    order_userid: 0,
    order_user_fio: '',
    order_user_mail: '',
    order_user_phone: '',
    order_user_emiaslogin: null,
    order_user_wikilogin: null,
    order_user_tg_id: null,
    order_user_tg_name: null,
    order_text: '',
    order_created_at: null,
    order_modified_at: null,
    feedback_id: null,
    status_id: 0,
    status_name: '',
    space_id: 0,
    space_key: '',
    space_title: '',
    public_id: null,
    anonym_id: null,
    anonymorder_fio: null,
    anonymorder_speciality: null,
    anonymorder_muname: null,
    anonymorder_mail: null,
    anonymorder_phone: null,
    anonymorder_tg_id: null,
    order_attachments: [],
    order_unionrole_id: null,
    order_unionrole_name: '',
    order_unionrole_emiasid: null,
    order_union_roles: [],

    inwork_id: null,
    inwork_userid: null,
    inwork_user_fio: null,
    inwork_wikilogin: null,
    inwork_user_emiaslogin: null,
    inwork_user_phone: null,
    inwork_user_mail: null,
    inwork_user_tg_id: null,
    inwork_user_tg_name: null,

    answer_id: 0,
    answer_userid: null,
    answer_user_fio: null,
    answer_user_wikilogin: null,
    answer_user_emiaslogin: null,
    answer_user_phone: null,
    answer_user_mail: null,
    answer_text: null,
    answer_created_at: null,
    answer_modified_at: null,
    answer_user_tg_id: null,
    answer_user_tg_name: null,
    answer_attachments: [],

    new_order_upload_files: [],
    deny_order_upload_files: [],
    upload_order_infoarray: [],
    order_simul_files: 0,

    new_answer_upload_files: [],
    answer_simul_files: 0,
    deny_answer_upload_files: [],
    upload_answer_infoarray: [],

    is_update_active: 0

}